# Generated by Django 4.2.7 on 2023-11-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_employee_email_alter_employee_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='sname',
            new_name='last_name',
        ),
    ]
