# Generated by Django 4.2.7 on 2023-11-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_employee_email_alter_employee_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='amount',
        ),
    ]
