# Generated by Django 4.2.7 on 2023-11-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0005_remove_account_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="money_type",
            field=models.CharField(
                choices=[("credit", "Credit"), ("debit", "Debit")],
                default="credit",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_type",
            field=models.CharField(
                choices=[("income", "Income"), ("outcome", "Outcome")],
                default="income",
                max_length=7,
            ),
        ),
        migrations.DeleteModel(
            name="Account",
        ),
    ]
