# Generated by Django 4.2.7 on 2023-11-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0006_payment_money_type_alter_payment_transaction_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_price",
            field=models.IntegerField(default=0),
        ),
    ]
